FROM python:3-alpine3.8

RUN apk add git libmagic 

RUN git clone --depth=50 https://github.com/leadwire-apm/flamescope.git app  

RUN cd /app && \
   pip install --upgrade pip &&\
   pip3 install -r requirements.txt && \
   mkdir /profiles && \
   sed -i -e s/127.0.0.1/0.0.0.0/g -e s~examples~/profiles~g app/config.py

WORKDIR "/app"
ENTRYPOINT ["python", "run.py"]
EXPOSE 5000/tcp
