FROM osixia/openldap:1.4.0

ARG BUILD_DATE

MAINTAINER "Wassim Dhib" <wassim.dhib@leadwire.io>

LABEL org.label-schema.schema-version="leadwire-portail-${VERSION_PORTAIL}" \
    org.label-schema.name="Lead Wire APM" \
    org.label-schema.vendor="Lead Wire SAS" \
    org.label-schema.license="Private Use" \
    org.label-schema.build-date="${BUILD_DATE}"
    
    ENV LDAP_ORGANISATION="Leadwire Organization" \
    LDAP_DOMAIN="leadwire.io"
 
COPY /requirements/ldap/bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

EXPOSE 389
