FROM centos/systemd

MAINTAINER "Wassim Dhib" <wassim.dhib@leadwire.io>

LABEL org.label-schema.schema-version="leadwire-ldap-1.3" \
    org.label-schema.name="Lead Wire APM" \
    org.label-schema.vendor="Lead Wire SAS" \
    org.label-schema.license="Lead Wire Private Use" \
    org.label-schema.build-date="20200511"

##Update
RUN yum -y update

## TOOLS
RUN yum -y install sudo crontabs 


RUN yum install epel-release -y

RUN yum -y install openldap compat-openldap openldap-clients openldap-servers openldap-servers-sql openldap-devel && systemctl enable slapd.service

ADD /requirements/ /requirements/

RUN /usr/sbin/slapd -u ldap -h 'ldap:/// ldapi:///' && \
        /bin/sh /requirements/script/ldap-install.sh

EXPOSE 389 

CMD ["requirements/script/ldap-entrypoint.sh"]
