FROM centos:7
ARG BRANCH
RUN yum install -y git
RUN git clone --depth=50 --branch=${BRANCH} https://www.github.com/leadwire-apm/leadwire-portail.git /leadwire-portail

FROM centos:7
ARG VERSION_PORTAIL
ARG BUILD_DATE

MAINTAINER "Wassim Dhib" <wassim.dhib@leadwire.io>

LABEL org.label-schema.schema-version="leadwire-portail-${VERSION_PORTAIL}" \
    org.label-schema.name="Lead Wire APM" \
    org.label-schema.vendor="Lead Wire SAS" \
    org.label-schema.license="Private Use" \
    org.label-schema.build-date="${BUILD_DATE}"

## TOOLS
ADD /requirements/repo/mongodb-org-3.4.repo /etc/yum.repos.d/mongodb-org-3.4.repo

RUN yum -y install sudo crontabs unzip mongodb-org-shell openldap-servers 

#Repos
RUN yum install epel-release -y
RUN    curl -s https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -o epel-release-latest-7.noarch.rpm \ 
    && curl -s https://rpms.remirepo.net/enterprise/remi-release-7.rpm -o remi-release-7.rpm \ 
    && rpm -Uvh remi-release-7.rpm epel-release-latest-7.noarch.rpm \
    && rm -f remi-release-7.rpm epel-release-latest-7.noarch.rpm 

RUN yum install yum-utils \ 
    && yum-config-manager --enable remi-php74

## NGINX
##LEMON-LDAP NG
RUN yum install -y nginx && systemctl enable nginx
ADD /requirements/config/apm-nginx.conf /etc/nginx/conf.d/


# Necessary PHP Extensions
RUN yum --enablerepo=remi,remi-php74 install -y php-opcache php-pecl-apcu php-cli php-pear php-pecl-mongodb php-gd php-mbstring php-mcrypt php-xml php-ldap php-json

# Php-Fpm
RUN yum install -y php-fpm && systemctl enable php-fpm.service

ADD /requirements/config/www.conf /etc/php-fpm.d/www.conf
ADD /requirements/script/portail-install.sh /requirements/script/portail-install.sh
ADD /requirements/script/portail-entrypoint.sh /requirements/script/portail-entrypoint.sh

COPY --chown=nginx:nginx --from=0 /leadwire-portail /usr/share/leadwire-portail/

RUN sh /requirements/script/portail-install.sh \
  && rm -f /requirements/script/portail-install.sh

## OPENSSL
RUN mkdir -p /certificates/ && openssl req \
    -new \
    -newkey rsa:2048 \
    -days 3650 \
    -nodes \
    -x509 \
    -subj "/C=FR/ST=Paris/L=Paris/O=leadwire/CN=*.leadwire.io" \
    -keyout /certificates/server.key \
    -out /certificates/server.crt && openssl x509 -in /certificates/server.crt -out /certificates/server.pem -outform PEM

RUN mkdir -p /var/run/php-fpm/ && chown nginx:nginx /var/run/php-fpm/

CMD ("/requirements/script/portail-entrypoint.sh")

