FROM centos/systemd

MAINTAINER "Wassim Dhib" <wassim.dhib@leadwire.io>

LABEL org.label-schema.schema-version="leadwire-portail-1.3" \
    org.label-schema.name="Lead Wire APM" \
    org.label-schema.vendor="Lead Wire SAS" \
    org.label-schema.license="Lead Wire Private Use" \
    org.label-schema.build-date="20200502"

##Update
RUN yum -y update

## TOOLS
RUN yum -y install sudo unzip crontabs  

#Repos
RUN yum install epel-release -y
RUN curl -s http://rpms.remirepo.net/enterprise/remi-release-7.rpm -o remi-release-7.rpm && rpm -Uvh remi-release-7.rpm && yum install yum-utils -y && yum-config-manager --enable remi-php71 && rm -f remi-release-7.rpm

## NGINX
##LEMON-LDAP NG
RUN yum install -y nginx && systemctl enable nginx
ADD /requirements/config/apm-nginx.conf /etc/nginx/conf.d/


# Necessary PHP Extensions
RUN yum --enablerepo=remi,remi-php71 install -y php-opcache php-pecl-apcu php-cli php-pear php-pecl-mongodb php-gd php-mbstring php-mcrypt php-xml php-ldap php-json

# Php-Fpm
RUN yum install -y php-fpm && systemctl enable php-fpm.service
ADD /requirements/config/www.conf /etc/php-fpm.d/www.conf
##APM
ADD /requirements/ /requirements/

ARG VERSION_LEADWIRE
RUN sh /requirements/script/apm-install.sh

## OPENSSL
RUN mkdir -p /certificates/ && openssl req \
    -new \
    -newkey rsa:2048 \
    -days 3650 \
    -nodes \
    -x509 \
    -subj "/C=FR/ST=Paris/L=Paris/O=leadwire/CN=*.leadwire.io" \
    -keyout /certificates/server.key \
    -out /certificates/server.crt && openssl x509 -in /certificates/server.crt -out /certificates/server.pem -outform PEM

RUN mkdir -p /var/run/php-fpm/ && chown nginx:nginx /var/run/php-fpm/

CMD ("/requirements/script/portail-entrypoint.sh")
