FROM centos:7
ARG VERSION_SENTINL
RUN yum install -y unzip  git 
RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -
RUN yum install -y  nodejs 
RUN curl -sL https://github.com/leadwire-apm/reports/archive/v${VERSION_SENTINL}.zip -o v${VERSION_SENTINL}.zip && unzip v${VERSION_SENTINL}.zip && mv reports-${VERSION_SENTINL} sentinl  && cd sentinl && npm install 

ARG VERSION_ODFE
FROM amazon/opendistro-for-elasticsearch-kibana:$VERSION_ODFE

ARG BUILD_DATE

MAINTAINER "Wassim Dhib" <wassim.dhib@leadwire.io>

LABEL org.label-schema.schema-version="leadwire-kibana-${VERSION_ODFE}" \
    org.label-schema.name="Lead Wire APM" \
    org.label-schema.vendor="Lead Wire SAS" \
    org.label-schema.license="Private Use" \
    org.label-schema.build-date="${BUILD_DATE}"


## TOOLS
USER root
RUN yum -y install crontabs pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc

USER 1000

ENV NODE_OPTIONS="--max-old-space-size=4096"

COPY --chown=kibana:kibana --from=0 /sentinl /usr/share/kibana/plugins/sentinl/

RUN rm -fr /usr/share/kibana/optimize/*  /tmp/requirements

EXPOSE 5601

CMD ["/usr/local/bin/kibana-docker"]
