FROM debian:stable

ARG BUILD_DATE

MAINTAINER "Wassim Dhib" <wassim.dhib@leadwire.io>

LABEL org.label-schema.schema-version="leadwire-portail-${VERSION_PORTAIL}" \
    org.label-schema.name="Lead Wire APM" \
    org.label-schema.vendor="Lead Wire SAS" \
    org.label-schema.license="Private Use" \ 
    org.label-schema.build-date="${BUILD_DATE}"

ENV SSODOMAIN=example.com \
    LOGLEVEL=info \
    DEBIAN_FRONTEND=noninteractive



RUN echo "# Install LemonLDAP::NG source repo" && \
    apt-get -y update && \
    apt-get -y install wget apt-transport-https gnupg dumb-init && \
    wget -O - https://lemonldap-ng.org/_media/rpm-gpg-key-ow2 | apt-key add - && \
    echo "deb https://lemonldap-ng.org/deb 2.0 main" >/etc/apt/sources.list.d/lemonldap-ng.list

RUN apt-get -y update && \
    echo "# Install LemonLDAP::NG packages" && \
    apt-get -y install nginx lemonldap-ng cron anacron liblasso-perl libio-string-perl && \
    
    echo "# Install LemonLDAP::NG TOTP requirements" && \
    apt-get -y install libconvert-base32-perl libdigest-hmac-perl lemonldap-ng-fastcgi-server make libextutils-pkgconfig-perl libmodule-build-tiny-perl libnet-smtps-perl libmodule-pluggable-perl libemail-simple-perl \
    libhttp-throwable-perl libmoox-types-mooselike-numeric-perl  libtest-fatal-perl libemail-sender-perl \
    libcapture-tiny-perl libemail-abstract-perl libemail-address-perl cpanminus

RUN cd /usr/local/share && cpanm Email::Sender::Transport::SMTPS; exit 0
RUN cd /usr/local/share && perl -MCPAN -e 'install Email::Sender::Transport::SMTPS'
RUN cd /usr/local/share && perl -MCPAN -e 'install GD::SecurityImage'
RUN cd /usr/local/share && cpanm Apache::Session::Store::LDAP; exit 0 && \
    
    echo "# Install some DB drivers" && \
    apt-get -y install libdbd-mysql-perl libdbd-pg-perl && \
    echo "\ndaemon off;" >> /etc/nginx/nginx.conf

COPY /requirements/script/lemonldap-entrypoint.sh /

RUN echo '# Copy orignal configuration' && \
    cp -a /etc/lemonldap-ng /etc/lemonldap-ng-orig && \
    cp -a /var/lib/lemonldap-ng/conf /var/lib/lemonldap-ng/conf-orig && \
    cp -a /var/lib/lemonldap-ng/sessions /var/lib/lemonldap-ng/sessions-orig && \
    cp -a /var/lib/lemonldap-ng/psessions /var/lib/lemonldap-ng/psessions-orig

RUN echo "# Install nginx configuration files" && \
    cd /etc/nginx/sites-enabled/ && \
    ln -s ../../lemonldap-ng/handler-nginx.conf && \
    ln -s ../../lemonldap-ng/portal-nginx.conf && \
    ln -s ../../lemonldap-ng/manager-nginx.conf && \
    ln -s ../../lemonldap-ng/test-nginx.conf


RUN echo "# Configure nginx to log to standard streams" && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log
    
    
RUN sed 's,/usr/share/fonts/default/Type1/,/usr/share/X11/fonts/urw-fonts/,g' -i /etc/ImageMagick-6/type-ghostscript.xml

ADD /requirements/ /requirements/

RUN cp /requirements/images/kibana.png /usr/share/lemonldap-ng/portal/htdocs/static/common/apps/kibana.png && \
    cp /requirements/images/leadwire-icon.jpg /usr/share/lemonldap-ng/portal/htdocs/static/common/apps/leadwire-icon.jpg && \ 
    cp /requirements/images/leadwire-bg.jpg /usr/share/lemonldap-ng/portal/htdocs/static/common/backgrounds/leadwire-bg.jpg && \
    mkdir -p /usr/share/lemonldap-ng/portal/htdocs/static/leadwire/logo/ && \
    cp /requirements/images/leadwire-logo.jpg /usr/share/lemonldap-ng/portal/htdocs/static/leadwire/logo/leadwire-logo.jpg && \
    cp /requirements/images/grafana.png /usr/share/lemonldap-ng/portal/htdocs/static/common/apps/grafana.png && \
    cp /requirements/images/prometheus.gif /usr/share/lemonldap-ng/portal/htdocs/static/common/apps/prometheus.gif && \
    cp /requirements/images/leadwire-favicon.png /usr/share/lemonldap-ng/portal/htdocs/static/common/favicon.ico && \
    cp /requirements/images/leadwire-favicon.png /usr/share/lemonldap-ng/manager/htdocs/static/logos/favicon.ico 

RUN mkdir -p /certificates/ && openssl req \
    -new \
    -newkey rsa:2048 \
    -days 3650 \
    -nodes \
    -x509 \
    -subj "/C=FR/ST=Paris/L=Paris/O=leadwire/CN=*.leadwire.io" \
    -keyout /certificates/server.key \
    -out /certificates/server.crt && openssl x509 -in /certificates/server.crt -out /certificates/server.pem -outform PEM


VOLUME ["/etc/lemonldap-ng","/var/lib/lemonldap-ng/conf", "/var/lib/lemonldap-ng/sessions", "/var/lib/lemonldap-ng/psessions"]


RUN sed -i "s/example\.com/leadwire.io/g" /etc/nginx/sites-enabled/* /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-1.json  && \
   /usr/sbin/nginx 
   RUN service lemonldap-ng-fastcgi-server start 
   RUN sh /requirements/script/lemonldap-install.sh



EXPOSE 80 443 

RUN chmod 755 /requirements/script/lemonldap-entrypoint.sh && \
      sed -i 's# \$lmremote_custom##g' /etc/nginx/*.conf 

CMD ["/requirements/script/lemonldap-entrypoint.sh"]
